# Generated by Django 3.1.7 on 2021-03-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Recipes',
        ),
    ]
