# Generated by Django 3.1.7 on 2021-03-08 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_remove_recipes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes',
            name='cook_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='cook_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='degree',
            field=models.CharField(choices=[('Farentheitt', 'Farentheitt'), ('Celsius', 'Celsius')], default='Farentheitt', max_length=15),
        ),
        migrations.AddField(
            model_name='recipes',
            name='foodtype',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='prep_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='published',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Public'), ('Approval', 'Private'), ('Archived', 'Archived')], default='Draft', max_length=15),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='type_meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], default='Lunch', max_length=15),
        ),
        migrations.AddField(
            model_name='recipes',
            name='yeild',
            field=models.FloatField(null=True),
        ),
    ]
