# Generated by Django 3.1.7 on 2021-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_yields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.FloatField(null=True),
        ),
    ]
