# Generated by Django 3.1.7 on 2021-03-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_yields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type_meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], default='Breakfast', max_length=15),
        ),
    ]
